services:
  db:
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usedcar
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
